### ISSUE TITLE
Error when releasing mouse button outside of window.

### ISSUE THREAD

**Issue by GeertJohan** [go-flutter-desktop/go-flutter#113]
Doesn't seem to break any behavior, but is annoying nonetheless, and simply shouldn't occur.

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 260 pos 18: '_pointers.containsKey(datum.device)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:260:18)
#3      _SyncIterator.moveNext (dart:core/runtime/lib/core_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 343 pos 18: '_pointers.containsKey(datum.device)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:343:18)
#3      _SyncIterator.moveNext (dart:core/runtime/lib/core_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by tgienger** [comment]
I'm getting this just moving my cursor over the application. No button presses necessary.

**Comment by GeertJohan** [comment]
@tgienger: update to flutter 1.3.8 or higher
```
flutter channel beta
flutter upgrade
```
