### ISSUE TITLE
debug spam

### ISSUE THREAD

**Issue by symkuangyaw** [go-flutter-desktop/go-flutter#117]
after today update my console is spammed with errors like this,
how to fix this ?
also how to stop the auto update ? 

btw I'm using hover to run and debug my app

million thanks for this amazing tools, combined with hover... I can get rid of the most annoying part of android development (emulator, gradle, android studio)

```
[ERROR:e:\b\rr\tmpxc66kk\w\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 262 pos 18: 'state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:262:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by GeertJohan** [comment]
@symkuangyaw This happens if you have an older version of flutter. When you update to flutter 1.3.8 (beta channel) you shouldn't get spammed with this error anymore. Except for this specific situation: #113 

```
flutter channel beta
flutter upgrade
```

**Comment by symkuangyaw** [comment]
ah I see... I'm using stable channel atm.
many thanks @GeertJohan
