### ISSUE TITLE
When running any of the examples, I get unhandled exceptions when moving mouse over app

### ISSUE THREAD

**Issue by LampeMW** [go-flutter-desktop/go-flutter#119]
Example name: simple_demo
Examples repository version: 6bb17c4028be6fa3433a1987575a25b8d2d76f50

## Flutter version

```
flutter --version
Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (8 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

## Steps to Reproduce

When running 'hover run', the app starts up and I can see the window with the app inside, but as soon as I move my mouse over the app window, I get tons of repeated exceptions in console.

```
hover run
Using engine from cache
go: finding github.com/go-gl/glfw latest
[ERROR:e:\b\rr\tmpxc66kk\w\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(89)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:e:\b\rr\tmpxc66kk\w\src\flutter\shell\platform\embedder\embedder_surface_gl.cc(89)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:50300/
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":81.28,"monitorWidthMm":600,"monitorWidthSc":1920,"mscpi":81.28,"pixelRatio":0.508,"ppsc":1,"windowWidthPx":800,"windowWidthSc":800}
go-flutter: no method handler registered for method 'SystemChrome.setSystemUIOverlayStyle' on channel 'flutter/platform'
Syncing files to device Flutter test device...                   1,074ms

�  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Flutter test device is available at: http://127.0.0.1:50300/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[ERROR:e:\b\rr\tmpxc66kk\w\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 260 pos 18: '_pointers.containsKey(datum.device)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:260:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

[ERROR:e:\b\rr\tmpxc66kk\w\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 260 pos 18: '_pointers.containsKey(datum.device)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:260:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

[ERROR:e:\b\rr\tmpxc66kk\w\src\flutter\lib\ui\ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 260 pos 18: '_pointers.containsKey(datum.device)': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:260:18)
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

**Comment by GeertJohan** [comment]
Please use flutter at beta channel for compatibilty with go-flutter.
```
flutter chanel beta
flutter upgrade
```
