### ISSUE TITLE
hover run results in "panic: runtime error: index out of range"

### ISSUE THREAD

**Issue by canadaduane** [go-flutter-desktop/go-flutter#121]
## Flutter version

```
Flutter 1.4.9-hotfix.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 88fa7ea403 (4 days ago) • 2019-04-11 14:01:46 -0700
Engine • revision 4737fc5cd8
Tools • Dart 2.2.1 (build 2.2.1-dev.4.0 None)
```

## Golang errors (Optional)

```
hover run
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/go-flutter-desktop/hover/internal/enginecache.ValidateOrUpdateEngine(0x149f7c6, 0x6, 0xc000344140, 0x33)
	/Users/dujohnson/go/src/github.com/go-flutter-desktop/hover/internal/enginecache/cache.go:279 +0x2123
github.com/go-flutter-desktop/hover/cmd.build(0xc0003fa310, 0xa, 0x149f7c6, 0x6, 0xc000349d38, 0x1, 0x1)
	/Users/dujohnson/go/src/github.com/go-flutter-desktop/hover/cmd/build.go:66 +0x285
github.com/go-flutter-desktop/hover/cmd.glob..func5(0x1829700, 0x184c760, 0x0, 0x0)
	/Users/dujohnson/go/src/github.com/go-flutter-desktop/hover/cmd/run.go:31 +0x9f
github.com/spf13/cobra.(*Command).execute(0x1829700, 0x184c760, 0x0, 0x0, 0x1829700, 0x184c760)
	/Users/dujohnson/go/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x18294a0, 0x1, 0x1, 0x149ebad)
	/Users/dujohnson/go/src/github.com/spf13/cobra/command.go:850 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dujohnson/go/src/github.com/spf13/cobra/command.go:800
github.com/go-flutter-desktop/hover/cmd.Execute()
	/Users/dujohnson/go/src/github.com/go-flutter-desktop/hover/cmd/root.go:19 +0x32
main.main()
	/Users/dujohnson/go/src/github.com/go-flutter-desktop/hover/main.go:8 +0x20
```

## Steps to Reproduce

0. using flutter stable:
1. `flutter create myproject`
2. `cd myproject`
3. `hover init github.com/canadaduane/myproject`
4. create `main_desktop.dart` following readme instructions
5. `hover build`
6. `hover run`
7. break ^C
8. `flutter channel beta`
9. `hover run`

I missed a `flutter upgrade` step when moving from flutter `stable` to `beta`. This may have something to do with the result? When I do `flutter upgrade` and try again, however, I get the same "panic" result.

**Comment by GeertJohan** [comment]
This has beend fixed in https://github.com/go-flutter-desktop/hover/commit/cd01714c57e728b7ca2f21427752a0d0c987ada0
