### ISSUE TITLE
Windows /bin/ld.exe: cannot find -lflutter_engine

### ISSUE THREAD

**Issue by SahandAkbarzadeh** [go-flutter-desktop/go-flutter#122]
## Flutter version
```
Flutter 1.3.14-pre.66 • channel master • https://github.com/flutter/flutter.git
Framework • revision 91b71ba964 (3 weeks ago) • 2019-03-24 16:18:43 -0400
Engine • revision dcc72c7176
Tools • Dart 2.2.1 (build 2.2.1-dev.2.0 None)
```

## Steps to reproduce

run `hover run` on a new project.

output:

```

C:\Users\USERNAME\Desktop\flutter_desktop_example\a1\desktest>hover build
Using engine from cache
go: finding github.com/go-gl/glfw latest
# github.com/go-flutter-desktop/go-flutter/embedder
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Users\USERNAME\AppData\Local\hover\engine\windows/flutter_engine.dll when searching for -lflutter_engine
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/flutter_engine.dll when searching for -lflutter_engine
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:\Users\USERNAME\AppData\Local\hover\engine\windows/flutter_engine.dll when searching for -lflutter_engine
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/flutter_engine.dll when searching for -lflutter_engine
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lflutter_engine
collect2.exe: error: ld returned 1 exit status
Go get -u github.com/go-flutter-desktop/go-flutter failed: exit status 2
```

```

**Comment by GeertJohan** [comment]
I wonder why it shows the dll as incompatible... Are you running on a 32 bit system?

**Comment by SahandAkbarzadeh** [comment]
@GeertJohan 
no 
` Windows 10 1809 LSTC X64 (17763.437) `

**Comment by SahandAkbarzadeh** [comment]
@GeertJohan is it helpful to you if I build the engine myself to check if it works ?

**Comment by GeertJohan** [comment]
That could help, yes.
I dont know how a dll is decided to be incompatible..
Have you tried using hover with flutter at version 1.3.8? The current version at channel beta.

```
flutter channel beta
flutter upgrade
hover run
```

Please let me know if that works.

**Comment by SahandAkbarzadeh** [comment]
using beta channel causes this error for hover
( i also deleted `.../hover/engine` folder )

```
$ hover run
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/go-flutter-desktop/hover/internal/enginecache.ValidateOrUpdateEngine(0x897289, 0x7, 0xc00040ba80, 0x32)
        C:/Users/***/go/src/github.com/go-flutter-desktop/hover/internal/enginecache/cache.go:279 +0x20d1
github.com/go-flutter-desktop/hover/cmd.build(0xc00001c440, 0x11, 0x897289, 0x7, 0x0, 0x0, 0x0)
        C:/Users/***/go/src/github.com/go-flutter-desktop/hover/cmd/build.go:66 +0x28b
github.com/go-flutter-desktop/hover/cmd.glob..func1(0xc05940, 0xc27658, 0x0, 0x0)
        C:/Users/***/go/src/github.com/go-flutter-desktop/hover/cmd/build.go:36 +0x7f
github.com/spf13/cobra.(*Command).execute(0xc05940, 0xc27658, 0x0, 0x0, 0xc05940, 0xc27658)
        C:/Users/***/go/src/github.com/spf13/cobra/command.go:766 +0x2b5
github.com/spf13/cobra.(*Command).ExecuteC(0xc05e00, 0x1, 0x1, 0x895f0d)
        C:/Users/***/go/src/github.com/spf13/cobra/command.go:850 +0x303
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/***/go/src/github.com/spf13/cobra/command.go:800
github.com/go-flutter-desktop/hover/cmd.Execute()
        C:/Users/***/go/src/github.com/go-flutter-desktop/hover/cmd/root.go:19 +0x39
main.main()
        C:/Users/***/go/src/github.com/go-flutter-desktop/hover/main.go:8 +0x27
```

i think in [here](https://github.com/go-flutter-desktop/hover/blob/56b21444c2fdec4ed358a253b5b9be14d7581c50/internal/enginecache/cache.go#L279) it doesn't find any suitable version.

**Comment by GeertJohan** [comment]
@SahandAkbarzadeh Correct, that has been fixed in https://github.com/go-flutter-desktop/hover/commit/cd01714c57e728b7ca2f21427752a0d0c987ada0

**Comment by SahandAkbarzadeh** [comment]
@GeertJohan 
after updating hover to https://github.com/go-flutter-desktop/hover/commit/cd01714c57e728b7ca2f21427752a0d0c987ada0 and changing flutter channel to beta, `hover run` worked without any error.

thanks
