### ISSUE TITLE
app closed directly

### ISSUE THREAD

**Issue by Ali1Ammar** [go-flutter-desktop/go-flutter#192]
Hello
I have problem with hover 
I  create new project and add main_desktop.dart
then run
hover init github.com/my-organization/simpleApplication
hover run
app run and close directly
with this error 
hover: app 'my_awesome_ap' exited with error: exit status 2
* i use lubuntu 18.04*
## Flutter version
[✓] Flutter (Channel master, v1.8.1, on Linux, locale en_US.UTF-8)
 
## Error 

```
Using engine from cache
go: finding github.com/go-gl/glfw latest
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# github.com/go-gl/glfw/v3.2/glfw
In file included from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/c_glfw_linbsd.go:24:0:
../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/linux_joystick.c: In function ‘_glfwInitJoysticksLinux’:
../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/linux_joystick.c:224:42: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size 9 [-Wformat-truncation=]
             snprintf(path, sizeof(path), "%s/%s", dirname, entry->d_name);
                                          ^~~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from /usr/include/X11/Xcursor/Xcursor.h:26,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/x11_platform.h:39,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/internal.h:169,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/glfw/src/x11_init.c:28,
                 from ../../../goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/c_glfw_linbsd.go:19:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 12 and 267 bytes into a destination of size 20
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:50300/xafYBkzY6lo=/
Flutter is taking longer than expected to report its views. Still trying...
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":131.09677419354838,"monitorWidthMm":310,"monitorWidthSc":1600,"mscpi":131.09677419354838,"pixelRatio":0.8193548387096774,"ppsc":1,"windowWidthPx":800,"windowWidthSc":800}
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ff833ad33b6]

runtime stack:
runtime.throw(0x57e4cc, 0x2a)
	/home/aliammar125/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/home/aliammar125/go/src/runtime/signal_unix.go:374 +0x4a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x525800, 0xc000097928, 0xc0000824e0)
	/home/aliammar125/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0000978f8 sp=0xc0000978c0 pc=0x40d9fb
github.com/go-flutter-desktop/go-flutter/embedder._Cfunc_FlutterEngineSendPlatformMessage(0x1216400, 0xc0000824e0, 0xc000000000)
	_cgo_gotypes.go:317 +0x4d fp=0xc000097928 sp=0xc0000978f8 pc=0x4d9e0d
github.com/go-flutter-desktop/go-flutter/embedder.(*FlutterEngine).SendPlatformMessage.func2(0xc000106000, 0xc0000824e0, 0x13b1700)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/embedder/embedder.go:265 +0xda fp=0xc000097968 sp=0xc000097928 pc=0x4db97a
github.com/go-flutter-desktop/go-flutter/embedder.(*FlutterEngine).SendPlatformMessage(0xc000106000, 0xc0000979d0, 0x5409e0)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/embedder/embedder.go:265 +0xd7 fp=0xc0000979b8 sp=0xc000097968 pc=0x4db087
github.com/go-flutter-desktop/go-flutter.(*messenger).Send(0xc0000822a0, 0x578afb, 0x11, 0xc0000185c0, 0x19, 0x20, 0x0, 0x0, 0x5407e0, 0xc000097a01, ...)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/messenger.go:41 +0x92 fp=0xc000097a10 sp=0xc0000979b8 pc=0x50e2d2
github.com/go-flutter-desktop/go-flutter/plugin.(*BasicMessageChannel).Send(0xc00005c200, 0x5409e0, 0xc000012790, 0xc000024070, 0xc000024000, 0xc000097b08, 0x4a2f91)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/plugin/basic-message-channel.go:65 +0x87 fp=0xc000097a78 sp=0xc000097a10 pc=0x507477
github.com/go-flutter-desktop/go-flutter.(*lifecyclePlugin).glfwIconifyCallback(0x89dcf0, 0xc0000aa080, 0xc0000ac000)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/lifecycle.go:36 +0x83 fp=0xc000097b18 sp=0xc000097a78 pc=0x50e143
github.com/go-flutter-desktop/go-flutter.(*lifecyclePlugin).glfwIconifyCallback-fm(0xc0000aa080, 0x1174400)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/lifecycle.go:28 +0x3d fp=0xc000097b40 sp=0xc000097b18 pc=0x51367d
github.com/go-gl/glfw/v3.2/glfw.goWindowIconifyCB(0x11744a0, 0x300000000)
	/home/aliammar125/goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:218 +0x56 fp=0xc000097b68 sp=0xc000097b40 pc=0x4d5256
github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_f57d0873e1f1_goWindowIconifyCB(0x11744a0, 0x7ff800000000)
	_cgo_gotypes.go:2290 +0x33 fp=0xc000097b88 sp=0xc000097b68 pc=0x4d3003
runtime.call32(0x0, 0x7ffd7de6cea0, 0x7ffd7de6cf30, 0x10)
	/home/aliammar125/go/src/runtime/asm_amd64.s:519 +0x3b fp=0xc000097bb8 sp=0xc000097b88 pc=0x45cf5b
runtime.cgocallbackg1(0x0)
	/home/aliammar125/go/src/runtime/cgocall.go:314 +0x177 fp=0xc000097c30 sp=0xc000097bb8 pc=0x40dd67
runtime.cgocallbackg(0x0)
	/home/aliammar125/go/src/runtime/cgocall.go:191 +0xc5 fp=0xc000097c98 sp=0xc000097c30 pc=0x40db55
runtime.cgocallback_gofunc(0x40da1f, 0x525190, 0xc000097d28, 0xc000097d10)
	/home/aliammar125/go/src/runtime/asm_amd64.s:773 +0x9b fp=0xc000097cb8 sp=0xc000097c98 pc=0x45e52b
runtime.asmcgocall(0x525190, 0xc000097d28)
	/home/aliammar125/go/src/runtime/asm_amd64.s:620 +0x42 fp=0xc000097cc0 sp=0xc000097cb8 pc=0x45e3c2
runtime.cgocall(0x525190, 0xc000097d28, 0x11744a0)
	/home/aliammar125/go/src/runtime/cgocall.go:131 +0x7f fp=0xc000097cf8 sp=0xc000097cc0 pc=0x40da1f
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwWaitEventsTimeout(0x3f90624dd2f1a9fc)
	_cgo_gotypes.go:2025 +0x41 fp=0xc000097d28 sp=0xc000097cf8 pc=0x4d2201
github.com/go-gl/glfw/v3.2/glfw.WaitEventsTimeout(0x3f90624dd2f1a9fc)
	/home/aliammar125/goproject/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:823 +0x2d fp=0xc000097d60 sp=0xc000097d28 pc=0x4d64dd
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc00008a340, 0x0, 0x0)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/application.go:229 +0xa1a fp=0xc000097ed0 sp=0xc000097d60 pc=0x50be3a
github.com/go-flutter-desktop/go-flutter.Run(0xc00000e0e0, 0x3, 0x4, 0x3, 0xc000097f78)
	/home/aliammar125/goproject/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.24.1/application.go:23 +0x4d fp=0xc000097f00 sp=0xc000097ed0 pc=0x50af6d
main.main()
	/home/aliammar125/Desktop/my_awesome_ap/desktop/cmd/main.go:24 +0x189 fp=0xc000097f98 sp=0xc000097f00 pc=0x514389
runtime.main()
	/home/aliammar125/go/src/runtime/proc.go:200 +0x20c fp=0xc000097fe0 sp=0xc000097f98 pc=0x436ddc
runtime.goexit()
	/home/aliammar125/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000097fe8 sp=0xc000097fe0 pc=0x45ec71
hover: app 'my_awesome_ap' exited with error: exit status 2
```

**Comment by Drakirus** [comment]
The compiler warnings is related to your gcc version, I've never saw them. 
Warnings or not, go-flutter compiles and the crash occurs at run time.

I think this issue is related to #189.

go-flutter should stay [compatible](https://github.com/go-flutter-desktop/go-flutter#flutter-version) with the beta channel of flutter. From my testing, `Flutter 1.8.2-pre.33 • channel master` works. 
That been said, does the errors occurs on the beta channel? (`flutter channel beta`), if not, it's a non bug!

**Comment by Drakirus** [comment]
Updating flutter fixes the issue. Look at  #189 for more information.
