### ISSUE TITLE
Delete all chars and input a new char will crash.

### ISSUE THREAD

**Issue by CaiJingLong** [go-flutter-desktop/go-flutter#221]
my flutter env:

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/caijinglong/Library/Flutter/flutter_dev
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0
```

The log :

```log
hover: Downloading engine for platform darwin-x64 at version fee001c93f...
hover: Download completed in 0.85s
hover: Downloading artifacts at version fee001c93f...
hover: Download completed in 0.98s
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel. ($ flutter channel beta)
Running "flutter pub get" in desktop...                             6.6s
go: finding github.com/go-gl/glfw latest
flutter: Observatory listening on http://127.0.0.1:50300/zOfGOS0kh9c=/
go-flutter: no handler found for channel flutter/isolate
This is taking longer than expected...
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
github.com/go-flutter-desktop/go-flutter.(*textinputPlugin).addChar(0x42afc60, 0xc0001a9af4, 0x1, 0x1)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.0/textinput_model.go:25 +0x314
github.com/go-flutter-desktop/go-flutter.(*textinputPlugin).glfwCharCallback(0x42afc60, 0xc0000e6100, 0xc000000031)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.0/textinput.go:113 +0x7d
github.com/go-gl/glfw/v3.2/glfw.goCharCB(0x6518490, 0x31)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/input.go:295 +0x51
github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_e91ead9994e1_goCharCB(0x6518490, 0x31)
	_cgo_gotypes.go:2107 +0x33
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwWaitEventsTimeout(0x3f90624dd2f1a9fc)
	_cgo_gotypes.go:1946 +0x41
github.com/go-gl/glfw/v3.2/glfw.WaitEventsTimeout(0x3f90624dd2f1a9fc)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:823 +0x2d
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc0000e2000, 0x0, 0x0)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.0/application.go:261 +0xb6a
github.com/go-flutter-desktop/go-flutter.Run(0xc0000d6060, 0x4, 0x4, 0x2, 0xc0000c9f78)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.0/application.go:23 +0x4d
main.main()
	/private/tmp/JsonToDart/Flutter/desktop/desktop/cmd/main.go:24 +0x189
hover: app 'json_to_dart' exited with error: exit status 2
```

using code: https://github.com/fluttercandies/JsonToDart/tree/master/Flutter/desktop 

---

Reproduce gif like this:

![Kapture 2019-08-03 at 15 50 38](https://user-images.githubusercontent.com/14145407/62409229-bb4dae00-b606-11e9-9a1e-4da97df2c778.gif)

**Comment by Drakirus** [comment]
"Fixed" by https://github.com/go-flutter-desktop/go-flutter/commit/83358fe362d0d4c48d8b2b67fd0ea9f90946ad41 tagged into `v0.27.1` 

It's not a go-flutter error the flutter framework one, the framework is sending wrong value of text editing range.
More info on https://github.com/flutter/flutter/issues/20016

On the go-flutter side, the go-flutter embedder will now detect wrong text editing range sent by the flutter framework and print a error message. I tried to keep a "working state" by not updating the text editing range, the result will lead to undesirable behavior, the issue is on the flutter side, not ours.

**Comment by Drakirus** [comment]
I made final adjustment in https://github.com/go-flutter-desktop/go-flutter/commit/194612a55026b5269a17ad5bf3497b04a34121f4
tag `v0.27.4`

**Comment by CaiJingLong** [comment]
This crash will not be repeated in 0.27.1 in the same way.

**Comment by Tokenyet** [comment]
Does this mean we could not use `_textEditController.clear();` now, because of this bug? I just encounter this issue, and see the log below:
```
go-flutter: recover from wrong editingState: invalid text selection: selectionBase:-1, selectionExtent:-1. Refer to flutter/flutter#20016
```

**Comment by Drakirus** [comment]
Per the [`TextEditingController.clear` documentation](https://api.flutter.dev/flutter/widgets/TextEditingController/clear.html) says:
```log
clear method
void clear () 

Set the value to empty.

After calling this function, text will be the empty string and the selection will be invalid.

[...]
```
I guess it is working as expected^^
I've added the `go-flutter: recover from wrong editingState:` to avoid go-flutter crash.
I don't think it's an issue, just a miss uses of the Flutter framework.
