### ISSUE TITLE
Input has a crash error.

### ISSUE THREAD

**Issue by CaiJingLong** [go-flutter-desktop/go-flutter#222]
Sometimes, I get the error when delete or input new char.
This error does not always occur.

```bash
flutter --version
Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (2 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0
```

```log
panic: runtime error: slice bounds out of range

goroutine 1 [running, locked to thread]:
github.com/go-flutter-desktop/go-flutter.(*textinputPlugin).sliceLeftChar(...)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.1/textinput_model.go:141
github.com/go-flutter-desktop/go-flutter.(*textinputPlugin).Backspace(0x42b0c80, 0x0)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.1/textinput_darwin.go:73 +0x1f2
github.com/go-flutter-desktop/go-flutter.(*textinputPlugin).glfwKeyCallback(0x42b0c80, 0xc0000e4100, 0x103, 0x33, 0x1, 0x0)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.1/textinput.go:166 +0x5e8
github.com/go-flutter-desktop/go-flutter.(*Application).Run.func8(0xc0000e4100, 0x103, 0x33, 0x1, 0x0)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.1/application.go:259 +0x63
github.com/go-gl/glfw/v3.2/glfw.goKeyCB(0x660bb10, 0x3300000103, 0x1)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/input.go:289 +0x79
github.com/go-gl/glfw/v3.2/glfw._cgoexpwrap_e91ead9994e1_goKeyCB(0x660bb10, 0x3300000103, 0x1)
	_cgo_gotypes.go:2094 +0x4b
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwWaitEventsTimeout(0x3f90624dd2f1a9fc)
	_cgo_gotypes.go:1946 +0x41
github.com/go-gl/glfw/v3.2/glfw.WaitEventsTimeout(0x3f90624dd2f1a9fc)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:823 +0x2d
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc0000e0000, 0x0, 0x0)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.1/application.go:273 +0xb82
github.com/go-flutter-desktop/go-flutter.Run(0xc0000d4060, 0x4, 0x4, 0x2, 0xc0000c7f78)
	/Users/caijinglong/code/go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.27.1/application.go:23 +0x4d
main.main()
	/private/tmp/JsonToDart/Flutter/desktop/desktop/cmd/main.go:24 +0x189
hover: app 'json_to_dart' exited with error: exit status 2
Lost connection to device.
```

**Comment by zephylac** [comment]
Can you reproduce the error ?

**Comment by Drakirus** [comment]
Does https://github.com/go-flutter-desktop/go-flutter/commit/4707364239ca3a1c435c14aece5f3e8eb6175076 fixes the issue ?

**Comment by CaiJingLong** [comment]
It seems to be ok.
But because I have no definite steps to reproduce the problem, I am not sure if I can close this issue.
