### ISSUE TITLE
Windows: Failed to create OpenGL context

### ISSUE THREAD

**Issue by nzlov** [go-flutter-desktop/go-flutter#248]
## Flutter version

```
Flutter 1.9.1+hotfix.1 • channel beta • https://github.com/flutter/flutter
Framework • revision a1fb3fabec (27 hours ago) • 2019-09-03 18:07:52 -0700
Engine • revision cc88fa45db
Tools • Dart 2.5.0
```

## Go Flutter Version

```
v0.29.0 
```

But `v0.28.0` work.

## Golang Version

```
go version go1.13 windows/amd64
```

## Windows version

```
Windows 10 1903
```

## Golang errors (Optional)

```
hover: Using engine from cache
go: finding github.com/go-gl/glfw latest
go: finding github.com/go-gl/gl latest
creating glfw window: VersionUnavailable: WGL: Failed to create OpenGL context
hover: app 'xx' exited with error: exit status 1
```

## Steps to Reproduce

```
hover run
```

**Comment by nzlov** [comment]
Related to this #219 set OpenGL version  `4.1`.

**Comment by Drakirus** [comment]
does your project works with `hover run -b '@gl-3.3'`

**Comment by Drakirus** [comment]
@zephylac @nzlov can you check if the https://github.com/go-flutter-desktop/examples/tree/master/texture_tutorial example works on your OS (MacOS, and Windows)

**Comment by zephylac** [comment]
@Drakirus  I'll try ASAP

**Comment by nzlov** [comment]
@Drakirus My project is working, but [https://github.com/go-flutter-desktop/examples/tree/master/texture_tutorial](https://github.com/go-flutter-desktop/examples/tree/master/texture_tutorial)  is not, Because dependencies required to run on Windows are simply too complex。

**Comment by Drakirus** [comment]
@nzlov can you check to texture_tutorial with the following `go/cmd/options.go` file.
```go
package main

import (
	"github.com/go-flutter-desktop/go-flutter"
	"github.com/go-flutter-desktop/plugins/go-texture-example/example_image"
)

var options = []flutter.Option{
	flutter.WindowInitialDimensions(1200, 500),
	// flutter.AddPlugin(&example_video.VideoPlugin{}),
	flutter.AddPlugin(&example_image.ImagePlugin{}),
}
```
(no additional dependencies required)

**Comment by zephylac** [comment]
first run is ending up like this:
```
hover: Using engine from cache
hover: Cleaning the build directory
hover: Bundling flutter app
hover: Checking available release on Github
hover: Compiling 'go-flutter' and plugins
hover: build finished, starting app...
hover: Running texture_tutorial in debug mode
go-flutter: WARNING error creating the resource window: VersionUnavailable: NSGL: Failed to create OpenGL context
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
[ERROR:flutter/shell/platform/embedder/embedder_surface_gl.cc(95)] Could not create a resource context for async texture uploads. Expect degraded performance. Set a valid make_resource_current callback on FlutterOpenGLRendererConfig.
flutter: Observatory listening on http://127.0.0.1:50300/tlUg_gCvhuE=/
texture_tutorial: Start video
go-flutter: no handler found for channel flutter/isolate
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x4216017, 0x2a)
	/usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x4a9
runtime.asmcgocall(0x7000076de3b8, 0x4052f43)
	/usr/local/go/src/runtime/asm_amd64.s:639 +0x70

goroutine 17 [syscall, locked to thread]:
runtime.cgocall(0x416e740, 0xc000056d50, 0x0)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc000056d20 sp=0xc000056ce8 pc=0x400561b
github.com/go-gl/gl/v4.6-core/gl._Cfunc_glowGenTextures(0x0, 0x1, 0xc0000fcb38)
	_cgo_gotypes.go:7670 +0x45 fp=0xc000056d50 sp=0xc000056d20 pc=0x4116c85
github.com/go-gl/gl/v4.6-core/gl.GenTextures(...)
	.../go/pkg/mod/github.com/go-gl/gl@v0.0.0-20190320180904-bf2b1f2f34d7/v4.6-core/gl/package.go:9715
github.com/go-flutter-desktop/go-flutter.(*TextureRegistry).handleExternalTexture(0xc000022240, 0x2, 0x280, 0x168, 0x831f9a0)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/texture-registry.go:121 +0x26c fp=0xc000056de8 sp=0xc000056d50 pc=0x4147bfc
github.com/go-flutter-desktop/go-flutter.(*TextureRegistry).handleExternalTexture-fm(0x2, 0x280, 0x168, 0xc000056e70)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/texture-registry.go:94 +0x48 fp=0xc000056e20 sp=0xc000056de8 pc=0x4149a28
github.com/go-flutter-desktop/go-flutter/embedder.proxy_gl_external_texture_frame_callback(0xc0000e6018, 0x2, 0x280, 0x168, 0x7000076de540, 0x4055436)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/embedder/embedder_proxy.go:73 +0x4b fp=0xc000056e50 sp=0xc000056e20 pc=0x411444b
github.com/go-flutter-desktop/go-flutter/embedder._cgoexpwrap_84ad20d147fe_proxy_gl_external_texture_frame_callback(0xc0000e6018, 0x2, 0x280, 0x168, 0x7000076de540, 0x42c5648b43b3fc6e)
	_cgo_gotypes.go:655 +0x53 fp=0xc000056e90 sp=0xc000056e50 pc=0x4113183
runtime.call64(0x0, 0x7000076de420, 0x7000076de4b0, 0x30)
	/usr/local/go/src/runtime/asm_amd64.s:520 +0x3b fp=0xc000056ee0 sp=0xc000056e90 pc=0x40554fb
runtime.cgocallbackg1(0x0)
	/usr/local/go/src/runtime/cgocall.go:314 +0x177 fp=0xc000056f58 sp=0xc000056ee0 pc=0x4005987
runtime.cgocallbackg(0x0)
	/usr/local/go/src/runtime/cgocall.go:191 +0xc5 fp=0xc000056fc0 sp=0xc000056f58 pc=0x4005775
runtime.cgocallback_gofunc(0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/asm_amd64.s:773 +0x9b fp=0xc000056fe0 sp=0xc000056fc0 pc=0x4056a4b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000056fe8 sp=0xc000056fe0 pc=0x4057171

goroutine 1 [syscall, locked to thread]:
github.com/go-gl/glfw/v3.2/glfw._Cfunc_glfwWaitEventsTimeout(0x3f9999999999999a)
	_cgo_gotypes.go:1946 +0x41
github.com/go-gl/glfw/v3.2/glfw.WaitEventsTimeout(0x3f9999999999999a)
	.../go/pkg/mod/github.com/go-gl/glfw@v0.0.0-20190519095719-e6da0acd62b1/v3.2/glfw/window.go:823 +0x2d
github.com/go-flutter-desktop/go-flutter.(*Application).Run.func9(0x3f9999999999999a)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/application.go:308 +0x2d
github.com/go-flutter-desktop/go-flutter.(*EventLoop).WaitForEvents(0xc0000d0210, 0x4218a78)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/event-loop.go:126 +0x3f8
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc0000da000, 0x0, 0x0)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/application.go:307 +0xdbc
github.com/go-flutter-desktop/go-flutter.Run(0xc0000d00f0, 0x5, 0x6, 0x3, 0xc0000c7f78)
	.../go/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.29.0/application.go:22 +0x4d
main.main()
	.../Documents/devPerso/examples/texture_tutorial/go/cmd/main.go:24 +0x189

goroutine 34 [runnable, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1337 +0x1

goroutine 35 [syscall]:
github.com/3d0c/gmf._Cfunc_avcodec_send_packet(0x8b27e00, 0xc00019d8c0, 0xc000000000)
	_cgo_gotypes.go:2434 +0x4d
github.com/3d0c/gmf.(*CodecCtx).Decode.func2(0xc00016a020, 0xc00019d8c0, 0x0)
	.../go/pkg/mod/github.com/3d0c/gmf@v0.0.0-20190724130615-f4b5acb7db5c/codecCtx_go112.go:566 +0xe2
github.com/3d0c/gmf.(*CodecCtx).Decode(0xc00016a020, 0xc00019d8c0, 0x0, 0x0, 0xffffffffffffffff, 0xc00017c2d8, 0x1)
	.../go/pkg/mod/github.com/3d0c/gmf@v0.0.0-20190724130615-f4b5acb7db5c/codecCtx_go112.go:566 +0x6d
github.com/go-flutter-desktop/plugins/go-texture-example/example_video.(*ffmpegVideo).Stream(0xc000164040, 0xc00016a060)
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/video/ffmpeg-video.go:132 +0x18b
github.com/go-flutter-desktop/plugins/go-texture-example/example_video.(*VideoPlugin).InitPluginTexture.func2(0xc000012210, 0xc00016a060, 0xc0000fcb10)
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/video/main.go:60 +0xd7
created by github.com/go-flutter-desktop/plugins/go-texture-example/example_video.(*VideoPlugin).InitPluginTexture
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/video/main.go:57 +0xd0

goroutine 36 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:105 +0x159
github.com/go-flutter-desktop/plugins/go-texture-example/example_image.(*ImagePlugin).InitPluginTexture.func1(0xc0000fcb40)
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/image/main.go:38 +0x34
created by github.com/go-flutter-desktop/plugins/go-texture-example/example_image.(*ImagePlugin).InitPluginTexture
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/image/main.go:37 +0x88

goroutine 20 [sleep]:
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:307
time.Sleep(0x2625a00)
	/usr/local/go/src/runtime/time.go:105 +0x159
github.com/go-flutter-desktop/plugins/go-texture-example/example_video.(*VideoPlugin).InitPluginTexture.func1()
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/video/main.go:51 +0x8d
github.com/go-flutter-desktop/plugins/go-texture-example/example_video.(*ffmpegVideo).Stream.func2(0xc00016a060, 0xc0000ae004)
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/video/ffmpeg-video.go:163 +0x27
created by github.com/go-flutter-desktop/plugins/go-texture-example/example_video.(*ffmpegVideo).Stream
	.../Documents/devPerso/examples/texture_tutorial/go-texture-example/video/ffmpeg-video.go:162 +0x35e
hover: app 'texture_tutorial' exited with error: exit status 2
```

**Comment by Drakirus** [comment]
`gmf._Cfunc_avcodec_send_packet` this is related to `gmf` (the video plugin.)

In the same manner as my [above comment](https://github.com/go-flutter-desktop/go-flutter/issues/248#issuecomment-528813525), can you please try to run the example without the `VideoPlugin`?

**Comment by nzlov** [comment]
@Drakirus 
In windows.
use msys2.

```
$ hover run -b "@gl-3.3"
hover: Using engine from cache
hover: Cleaning the build directory
hover: failed to check your flutter channel: Unrecognized output formathover: Bundling flutter app
hover: Downloading 'go-flutter' @gl-3.3
go: finding github.com/go-flutter-desktop/go-flutter gl-3.3
go: finding github.com/go-gl/gl latest
go: finding github.com/go-gl/glfw latest
hover: 'go-flutter' is on version: v0.29.1-0.20190905111453-b8ad82c389c7
hover: Compiling 'go-flutter' and plugins
# pkg-config --cflags  -- libavutil libavformat libavcodec libavcodec libavutil libavcodec libavcodec libavutil libavfilter libavformat libavdevice libavfilter libavcodec libavutil libavcodec libavutil libavutil libavcodec libavutil libavformat libavcodec libswresample libswscale libavcodec libavutil
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavdevice was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavdevice.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavdevice' found
Package libavfilter was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavfilter.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavfilter' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
Package libavformat was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavformat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavformat' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libswresample was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswresample.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswresample' found
Package libswscale was not found in the pkg-config search path.
Perhaps you should add the directory containing `libswscale.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libswscale' found
Package libavcodec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavcodec.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavcodec' found
Package libavutil was not found in the pkg-config search path.
Perhaps you should add the directory containing `libavutil.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libavutil' found
pkg-config: exit status 1
hover: Go build failed: exit status 2
```

But run `pkg-config --libs libavformat`
```
$ pkg-config --libs libavformat
-L/usr/local/ffmpeg/lib -L/mingw64/lib -L/usr/local/ffmpeg/lib -L/mingw64/lib -L/usr/local/ffmpeg/lib -lavformat -lm -lz -lsecur32 -lws2_32 -lavcodec -lm -lz -lole32 -luser32 -lswresample -lm -lavutil -lm -luser32 -lbcrypt
```

**Comment by Drakirus** [comment]
I shouldn't have ask you to run the texture_example.
I've updated the [texture_tutorial](https://github.com/go-flutter-desktop/examples/tree/master/texture_tutorial), can you please retry?

**Comment by nzlov** [comment]
@Drakirus It's up and running.

**Comment by nzlov** [comment]
I found that the reason for this success is that you annotated the video plug-in code in `options.go`

**Comment by Drakirus** [comment]
> @Drakirus It's running, but there's no video, no pictures, just white.

Hummm?
Are you not seeing [this](https://github.com/go-flutter-desktop/examples/blob/master/texture_tutorial/test.png) image?

**Comment by nzlov** [comment]
Sorry, there was a picture at the beginning, but the warning was not wide enough.
When I widen it, it's just white.

**Comment by Drakirus** [comment]
Ok it's working as expected, the image should disappear after 5s of screen time.

**Comment by nzlov** [comment]
OK, thank you.
But how fo fix video plugin ?

**Comment by Drakirus** [comment]
well, there is a BIG Disclaimer in the [video_player](https://github.com/go-flutter-desktop/plugins/tree/master/video_player) repo..

I'm repeating myself
> does your system works with the [video-to-goImage](https://github.com/3d0c/gmf/blob/f4b5acb7db5cbbda9a6209be1d0de5f552823f62/examples/video-to-goImage.go) gmf example?

**Comment by nzlov** [comment]
Yes, I missed it, it is a problem with `gmf`.

**Comment by Drakirus** [comment]
Reopening this issue since we still need to decide whether or not we downgrade the OpenGL version from `4.1` to `3.3`.

**Comment by nzlov** [comment]
I am running `win10` on `macos` host via `Parallels Desktop`, and I don't know how it works on `win10` host.

**Comment by nzlov** [comment]
In windows. use `msys2`.
fix `pkg-config`:

```
pacman -S  mingw-w64-x86_64-pkg-config 
```

**Comment by ykmnkmi** [comment]
How to build with gl-3.1?

**Comment by Drakirus** [comment]
@ykmnkmi can you update your OpenGL driver?

**Comment by ykmnkmi** [comment]
last update 2011, but works with gl-3.3 on linux

**Comment by Drakirus** [comment]
```sh
$ hover build --help 
Flags:
      --opengl string       The OpenGL version specified here is only relevant for external texture plugin (i.e. video_plugin).
                            If 'none' is provided, texture won't be supported. Note: the Flutter Engine still needs a OpenGL compatible context. (default "3.3")
```

OpenGL is used in 2 way. 
  - One through GLFW, used to draw your flutter app handle event, etc..  
  - Two through OpenGL-bindings directly, ONLY for textures (as the above flag description says).
    But the OpenGL-bindings version used here affect GLFW internally.

By default, we use GLFW/3.2 and OpenGL-bindings 3.3, so your system must be compatible with those versions (at least OpenGL 3.3 or above). 

But if you don't have support for OpenGL 3.3. you could use the `--opengl=none` flag.
This flag will use OpenGL in one way:
  - through GLFW, used to draw your flutter app handle event, etc..  
  - Texture plugin won't be supported and panic the app.

GLFW will internally choose the min OpenGL version to use.

**Comment by joeblew99** [comment]
ok thanks for explaining it.

**Comment by lmx01** [comment]
I got this error while run "hover run -b '@gl-3.3'.
go get github.com/go-flutter-desktop/go-flutter@gl-3.3: github.com/go-flutter-desktop/go-flutter@gl-3.3: invalid version: unknown revision gl-3.3

This branch does not exist anymore,how can I solved this problem now ? thanks.

**Comment by pchampio** [comment]
Well, `hover run -b '@gl-3.3` is an older, which was deleted, as the error suggest.
Why do you want to use this very old branch?

**Comment by lmx01** [comment]
Sorry，I just didn't know how this works.I just want to solve the problem in Win10 while I run "hover run":
Windows: Failed to create OpenGL context

**Comment by pchampio** [comment]
update your graphic card driver or run
`hover run --opengl=none`

**Comment by lmx01** [comment]
```hover run --opengl=none``` can run,but not texture，it becames a white screen.My graphic card driver is newest also.

**Comment by pchampio** [comment]
`hover run --opengl=3.2`

**Comment by pchampio** [comment]
I won't be able to provide you with a fix, sorry.

**Comment by lmx01** [comment]
ok,thank U for your help also.
