### ISSUE TITLE
InvokeMethodWithReply throw exception

### ISSUE THREAD

**Issue by chengxuncc** [go-flutter-desktop/go-flutter#345]
## Hover doctor

```
$ hover doctor
←[1;36mhover: ←[0m←[32mRunning on windows←[0m
←[1;36mhover: ←[0m←[32mDocker installed: false←[0m
←[1;36mhover: ←[0m←[32mSharing flutter version←[0m
Flutter 1.12.13+hotfix.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 18cd7a3601 (6 weeks ago) • 2019-12-11 06:35:39 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
hover: Flutter engine commit: https://github.com/flutter/engine/commit/2994f7e1e6
hover: Finding out the C compiler version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module mutualcall/go

go 1.13

require (
        github.com/go-flutter-desktop/go-flutter v0.34.1
        github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
docker: false
hover: Sharing the content of go/cmd
go\cmd\main.go  go\cmd\options.go
```

## Error output

Run example app:
```
git clone https://github.com/chengxuncc/mutualcall.git
cd mutualcall
hover run
```
Then click FloatingActionButton and error show up:
```log
2020/01/22 12:01:26 hello from dart
flutter: say2
flutter: hello from golang
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

github.com/go-flutter-desktop/go-flutter/embedder.proxy_desktop_binary_reply(0xe7f8bd0, 0xf, 0xc000170088)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/embedder/embedder_proxy.go:102 +0x73
github.com/go-flutter-desktop/go-flutter/embedder._cgoexpwrap_fe39363eff7f_proxy_desktop_binary_reply(0xe7f8bd0, 0xf, 0xc000170088)
    _cgo_gotypes.go:687 +0x46
github.com/go-flutter-desktop/go-flutter/embedder._Cfunc_FlutterEngineRunTask(0xa27f890, 0xc00017e070, 0x0)
    _cgo_gotypes.go:362 +0x54
github.com/go-flutter-desktop/go-flutter/embedder.(*FlutterEngine).RunTask.func1(0xc00009c090, 0xc00017e070, 0xc00007faa0)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/embedder/embedder.go:282 +0x9e
github.com/go-flutter-desktop/go-flutter/embedder.(*FlutterEngine).RunTask(0xc00009c090, 0xc00017e070, 0xc00017e070)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/embedder/embedder.go:282 +0x3c
github.com/go-flutter-desktop/go-flutter.(*EventLoop).WaitForEvents(0xc000004760, 0x627e80)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/event-loop.go:115 +0x312
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc000098000, 0x0, 0x0)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/application.go:330 +0xef2
github.com/go-flutter-desktop/go-flutter.Run(0xc000004540, 0x4, 0x4, 0x2, 0xc00007ff40)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/application.go:27 +0x54
main.main()
    src/github.com/chengxuncc/mutualcall/go/cmd/main.go:24 +0x18f

goroutine 37 [chan receive]:
github.com/go-flutter-desktop/go-flutter.(*messenger).SendWithReply(0xc000060420, 0x61ab83, 0x14, 0xc000180080, 0x19, 0x40, 0x0, 0x0, 0x0, 0x0, ...)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/messenger.go:64 +0x2e7
github.com/go-flutter-desktop/go-flutter/plugin.(*MethodChannel).InvokeMethodWithReply(0xc000112000, 0x615554, 0x4, 0x5b8000, 0x64ae00, 0x0, 0x0, 0x0, 0x0)
    pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.34.1/plugin/method-channel.go:75 +0xc6
main.(*Greeting).hi.func1(0xc000006088)
    src/github.com/chengxuncc/mutualcall/go/cmd/options.go:29 +0x76
created by main.(*Greeting).hi
    src/github.com/chengxuncc/mutualcall/go/cmd/options.go:27 +0x4a
rax     0x0
rbx     0xf
rcx     0xf
rdi     0xc000170090
rsi     0xe7f8bd0
rbp     0xc00007f7d0
rsp     0xc00007f798
r8      0x0
r9      0x1
r10     0xc000170090
r11     0xffffffffffffffff
r12     0xa
r13     0x9
r14     0x200
r15     0x5b2ef18
rip     0x0
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
Lost connection to device.
hover: App 'mutualcall' exited with error: exit status 2
```

**Comment by pchampio** [comment]
@chengxuncc thanks for providing the mutualcall project.
It took me a looong time, but I managed to find the time and enough will to work on this segfault issue.
Man that was hard...

You can assert that my fix solves this issue by running: ` hover run -b '@fix_seg_fault' `.

**Comment by chengxuncc** [comment]
Wow thanks. It works like a charm.
