### ISSUE TITLE
Write file exception on windows.

### ISSUE THREAD

**Issue by sinojelly** [go-flutter-desktop/go-flutter#491]
## Hover doctor

```
D:\Develop\projects\github\MyProject>hover doctor
[1;36mhover: [0m[32mHover version v0.42.0 running on windows[0m
[1;36mhover: [0m[32mSharing flutter version[0m
Flutter 1.19.0-4.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8fe7655ed2 (10 days ago) • 2020-07-01 14:31:18 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/9a28c3bcf40ce64fee61e807ee3e1395fd6bd954
hover: Finding out the C compiler version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module github.com/sinojelly/SmartDdd/go

go 1.14

require (
        github.com/go-flutter-desktop/go-flutter v0.41.2
        github.com/go-flutter-desktop/plugins/path_provider v0.4.0
        github.com/miguelpruivo/flutter_file_picker/go v0.0.0-20200604215027-87ee48b7f3f6
        github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go\cmd\import-path_provider-plugin.go   go\cmd\main.go  go\cmd\options.go
```

## Error output

Using `file.writeAsString(content);` to write file to user dir, I get the following
error: (It works on iOS and Android)

```log
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: FileSystemException: Cannot open file, path = 'C:\Users\jelly\AppData\Local\com.jelly\MyProject/template_tasks.json' (OS Error: 系统找不到指定的路径。
, errno = 3)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
#1      _rootRunUnary (dart:async/zone.dart:1198:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#8      _rootRun (dart:async/zone.dart:1190:13)
#9      _CustomZone.run (dart:async/zone.dart:1093:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

**Comment by sinojelly** [comment]
I found the solution, 
On iOS & Android, no need to create app documents directory,
but on windows, should create the app documents directory first,  then write a file.
So the solution is creating the app documents directory first.
