### ISSUE TITLE
Some panic happen when I press some keys!

### ISSUE THREAD

**Issue by leedstyh** [go-flutter-desktop/go-flutter#502]
## Hover doctor

```
hover: Hover version v0.42.0 running on windows
hover: Sharing flutter version
Flutter 1.20.0-7.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision e606910f28 (10 days ago) • 2020-07-28 16:06:37 -0700
Engine • revision ac95267aef
Tools • Dart 2.9.0 (build 2.9.0-21.10.beta)
hover: Flutter engine commit: https://github.com/flutter/engine/commit/ac95267aef5175b3f6c3387d502070c68f588ad5
hover: Finding out the C compiler version
gcc (tdm64-1) 5.1.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

hover: Sharing the content of go.mod
module counter_test/go

go 1.14

require (
        github.com/go-flutter-desktop/go-flutter v0.41.2
        github.com/pkg/errors v0.9.1
)
hover: Sharing the content of hover.yaml
application-name: ""
executable-name: ""
package-name: ""
license: ""
target: lib/main_desktop.dart
branch: ""
cache-path: ""
opengl: ""
engine-version: ""
hover: Sharing the content of go/cmd
go\cmd\main.go  go\cmd\options.go
```

```
$ hover doctor
hover: Running on linux
hover: Docker installed: true
hover: Sharing flutter version
[...]
```

## Error output

Using `hover run` to run my application, I get the following

When I press `Shift Right` key:

```
go-flutter: recovered from panic while handling keydown event: InvalidValue: Invalid scancode
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0x5e, 0x0, 0x0)
        D:/App/go/src/runtime/debug/stack.go:24 +0xa4
runtime/debug.PrintStack()
        D:/App/go/src/runtime/debug/stack.go:16 +0x29
github.com/go-flutter-desktop/go-flutter/internal/keyboard.Normalize.func1(0x63acf4, 0x7)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/internal/keyboard/keyboard.go:63 +0x117
panic(0x608840, 0xc0001ca860)
        D:/App/go/src/runtime/panic.go:969 +0x174
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0x28040900, 0x100)
        D:/App/gopath/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:174 +0x21d
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        D:/App/gopath/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:185
github.com/go-gl/glfw/v3.3/glfw.GetKeyName(0xffffffffffffffff, 0x136, 0x400, 0x2030000)
        D:/App/gopath/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/input.go:446 +0x5e
github.com/go-flutter-desktop/go-flutter/internal/keyboard.Normalize(0xffffffffffffffff, 0x136, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/internal/keyboard/keyboard.go:68 +0xe3
github.com/go-flutter-desktop/go-flutter.(*keyeventPlugin).sendKeyEvent(0x7b4090, 0xc000088000, 0xffffffffffffffff, 0x136, 0x1, 0x1)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/key-events.go:42 +0x8f
github.com/go-flutter-desktop/go-flutter.(*Application).Run.func10(0xc000088000, 0xffffffffffffffff, 0x136, 0x1, 0x1)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/application.go:328 +0xac
github.com/go-gl/glfw/v3.3/glfw.goKeyCB(0xae530, 0x136ffffffff, 0x100000001)
        D:/App/gopath/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/input.go:359 +0x80
github.com/go-gl/glfw/v3.3/glfw._cgoexpwrap_b30766d4f379_goKeyCB(0xae530, 0x136ffffffff, 0x100000001)
        _cgo_gotypes.go:2612 +0x52
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwWaitEventsTimeout(0x3f9999999999999a)
        _cgo_gotypes.go:2476 +0x48
github.com/go-gl/glfw/v3.3/glfw.WaitEventsTimeout(0x3f9999999999999a)
        D:/App/gopath/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:994 +0x34
github.com/go-flutter-desktop/go-flutter.(*Application).Run.func12(0x3f9999999999999a)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/application.go:351 +0x34
github.com/go-flutter-desktop/go-flutter.(*EventLoop).WaitForEvents(0xc0000766c0, 0x650408)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/event-loop.go:120 +0x622
github.com/go-flutter-desktop/go-flutter.(*Application).Run(0xc00013c000, 0x0, 0x0)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/application.go:350 +0x11ce
github.com/go-flutter-desktop/go-flutter.Run(0xc000004c80, 0x3, 0x4, 0x3, 0xc000115f68)
        D:/App/gopath/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.41.2/application.go:26 +0x54
main.main()
        D:/code/counter_test/go/cmd/main.go:24 +0x18f
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: Unknown keymap for key events:
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new RawKeyEvent.fromMessage (package:flutter/src/services/raw_keyboard.dart:314:9)
flutter: #1      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:563:43)
flutter: #2      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
flutter: #3      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
flutter: #4      _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
flutter: #8      _invoke3 (dart:ui/hooks.dart:281:10)
flutter: #9      _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

When I press some other keys (like `m`, but not all the other keys):

```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 77 pos 16: 'keys.isNotEmpty':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:77:16)
flutter: #3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
flutter: #4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:181:63)
flutter: #5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:309:63)
flutter: #6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:472:20)
flutter: #7      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1623:43)
flutter: #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:598:68)
flutter: #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:76:49)
flutter: #10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:267:33)
flutter: #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:282:15)
flutter: #15     _invoke3 (dart:ui/hooks.dart:281:10)
flutter: #16     _dispatchPlatformMessage (dart:ui/hooks.dart:156:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## reproduce 

This happens even with a `Counter` example.

**Comment by JanezStupar** [comment]
I am getting this too. It doesn't happen on every application launch however. Some times all the keys are handled correctly.

**Comment by pchampio** [comment]
I know that pressing the `Calc` key on my keyboard triggers the GLFW error from: https://github.com/go-flutter-desktop/go-flutter/blob/fa6a0c7f740169f654d2996ec60d3dc2b4a0fb00/internal/keyboard/keyboard.go#L68
But I have no idea what to do..

**Comment by kokocooler2020** [comment]
I have the same issue too, when i press 'caps lock' key for input some chars.
any body help please?
