### ISSUE TITLE
Very fast input and delete

### ISSUE THREAD

**Issue by leielyq** [go-flutter-desktop/go-flutter#554]
GLFW: An invalid error was not accepted by the caller: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。
GLFW: Please report this bug in the Go package immediately.
panic: FormatUnavailable: Win32: Failed to convert clipboard to string: 操作成功完成。

goroutine 17 [running, locked to thread]:
github.com/go-gl/glfw/v3.3/glfw.acceptError(0x0, 0x0, 0x0, 0xc000004ee0, 0x1)
        D:/SDK/Go/Path/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:178 +0x208
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
        D:/SDK/Go/Path/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/error.go:185
github.com/go-gl/glfw/v3.3/glfw.PostEmptyEvent()
        D:/SDK/Go/Path/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20200707082815-5321531c36a2/window.go:1007 +0x3f
github.com/go-flutter-desktop/go-flutter.(*EventLoop).PostTask(0xc0000728a0, 0xf38ced0, 0x119399ba, 0x3c11ab81fbac)
        D:/SDK/Go/Path/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/event-loop.go:73 +0x139
github.com/go-flutter-desktop/go-flutter/embedder.proxy_post_task_callback(...)
        D:/SDK/Go/Path/pkg/mod/github.com/go-flutter-desktop/go-flutter@v0.42.0/embedder/embedder_proxy.go:94
github.com/go-flutter-desktop/go-flutter/embedder._cgoexpwrap_1d54f1096e3c_proxy_post_task_callback(0xf38ced0, 0x119399ba, 0x3c11ab81fbac, 0xc0000128d0)
        _cgo_gotypes.go:906 +0x53

**Comment by leielyq** [comment]
https://github.com/go-flutter-desktop/go-flutter/issues/537#issuecomment-743077935 niu!
