### ISSUE TITLE
go flutter initalize failed with ` Failed to lookup symbol 'bitsdojo_window_api':`

### ISSUE THREAD

**Issue by zw963** [go-flutter-desktop/go-flutter#641]
![image](https://user-images.githubusercontent.com/549126/150471676-d760b6ac-936d-4f4b-b2f3-ea57b618c3ce.png)

Following is backtrace:

```
hover: Using engine from cache
hover: Cleaning the build directory
hover: ⚠ The go-flutter project tries to stay compatible with the beta channel of Flutter.
hover: ⚠     It's advised to use the beta channel: `flutter channel beta`
hover: Bundling flutter app

💪 Building with sound null safety 💪

hover: Compiling 'go-flutter' and plugins
hover: Successfully compiled executable binary for linux
hover: Build finished, starting app...
hover: Running magpie_desktop_app in debug_unopt mode
go-flutter: calculated pixelRatio limited to a minimum of 1.0. metrics: {"dpi":108.37333333333333,"monitorWidthMm":600,"monitorWidthSc":2560,"mscpi":108.37333333333333,"pixelRatio":0.6773333333333333,"ppsc":1,"windowWidthPx":800,"windowWidthSc":800}
flutter: Observatory listening on http://127.0.0.1:50300/
hover: Connecting hover to 'magpie_desktop_app' for hot reload
flutter: Null check operator used on a null value
flutter: Null check operator used on a null value
go-flutter: no handler found for channel flutter/system_tray
go-flutter: no method handler registered for method 'selectSingleEntryHistory' on channel 'flutter/navigation'
go-flutter: no method handler registered for method 'routeInformationUpdated' on channel 'flutter/navigation'
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'bitsdojo_window_api': /home/zw963/Magpie/magpie-desktop-app/go/build/outputs/linux-debug_unopt/magpie_desktop_app: undefined symbol: bitsdojo_window_api
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
#1      bitsdojoWindowAPI (package:bitsdojo_window_linux/src/native_api.dart:118:6)
#2      bitsdojoWindowAPI (package:bitsdojo_window_linux/src/native_api.dart)
#3      _theAPI (package:bitsdojo_window_linux/src/native_api.dart:121:33)
#4      _theAPI (package:bitsdojo_window_linux/src/native_api.dart)
#5      getAppWindowHandle (package:bitsdojo_window_linux/src/native_api.dart:12:5)
#6      getAppWindowHandle (package:bitsdojo_window_linux/src/native_api.dart)
#7      new GtkAppWindow._ (package:bitsdojo_window_linux/src/app_window.dart:16:27)
#8      GtkAppWindow._instance (package:bitsdojo_window_linux/src/app_window.dart:20:54)
#9      GtkAppWindow._instance (package:bitsdojo_window_linux/src/app_window.dart)
#10     new GtkAppWindow (package:bitsdojo_window_linux/src/app_window.dart:23:12)
#11     BitsdojoWindowLinux.appWindow (package:bitsdojo_window_linux/src/bitsdojo_window_linux_real.dart:23:12)
#12     appWindow (package:bitsdojo_window/src/app_window.dart:42:20)
#13     app.<anonymous closure> (package:magpie_desktop_app/app.dart:38:17)
#14     BitsdojoWindowLinux.doWhenWindowReady.<anonymous closure> (package:bitsdojo_window_linux/src/bitsdojo_window_linux_real.dart:16:15)
#15     _rootRunUnary (dart:async/zone.dart:1436:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
```

**Comment by jld3103** [comment]
The problem is clearly related to the bitsdojo_window_linux package and I won't work on go-flutter.

**Comment by pchampio** [comment]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'bitsdojo_window_api': /home/zw963/Magpie/magpie-desktop-app/go/build/outputs/linux-debug_unopt/magpie_desktop_app: undefined symbol: bitsdojo_window_api
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:34:70)
```
This problem is about FFI loading. I don't know how it is handled.
