### ISSUE TITLE
Hover bug

### ISSUE THREAD

**Issue by Quackdoc** [go-flutter-desktop/go-flutter#674]
## Hover doctor

N/A
I Am running arch linux I have tried go `go 2:1.19-1` and compiling go-git

## Error output

```
Using `hover build [...] --XXX` to build my application, I get the following
error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x675366]

goroutine 1 [running]:
debug/elf.(*Section).ReadAt(0xc000212000?, {0xc0001fc000?, 0x270?, 0x24?}, 0x40?)
        <autogenerated>:1 +0x26
archive/zip.readDirectoryEnd({0x9e8fe0, 0xc0000acf80}, 0x210)
        /usr/lib/go/src/archive/zip/reader.go:526 +0xf5
archive/zip.(*Reader).init(0xc0000f7c70, {0x9e8fe0?, 0xc0000acf80}, 0x210)
        /usr/lib/go/src/archive/zip/reader.go:97 +0x5c
archive/zip.NewReader({0x9e8fe0, 0xc0000acf80}, 0x210)
        /usr/lib/go/src/archive/zip/reader.go:90 +0x5e
github.com/daaku/go%2ezipexe.zipExeReaderElf({0x9e99c0?, 0xc0000140d0}, 0xc99545)
        /home/quack/go/src/github.com/daaku/go.zipexe/zipexe.go:128 +0x8b
github.com/daaku/go%2ezipexe.NewReader({0x9e99c0, 0xc0000140d0}, 0x0?)
        /home/quack/go/src/github.com/daaku/go.zipexe/zipexe.go:48 +0x98
github.com/daaku/go%2ezipexe.OpenCloser({0xc00002a2d0?, 0xc0000cb980?})
        /home/quack/go/src/github.com/daaku/go.zipexe/zipexe.go:30 +0x57
github.com/GeertJohan/go%2erice.init.0()
        /home/quack/go/src/github.com/GeertJohan/go.rice/appended.go:42 +0x65
```

##
I had just installed hover for the first time on this install and running it leads to these issues

**Comment by pchampio** [comment]
@jld3103 do you know how to use https://github.com/go-flutter-desktop/hover/tree/master/assets ?
I actually don't^^

**Comment by jld3103** [comment]
It's a bug with go 1.19 and rice. The fix is to use go embed in hover instead. Can submit a PR tomorrow then I can fix it on my work time where we need this fix too :)
